#!/usr/bin/env bash
HISTSIZE=0
set +o history

#
# kickstarts build process for a basic server instance.
#
# OS: debian 11


# Make sure args are supplied
if [ $# -eq 0 ]
  then
    err "ERR | -FQDN -HOSTNAME -SSH_PORT -CERTBOT_EMAIL"
    exit 1
fi

DRY_RUN=TRUE

FQDN=$1
HOSTNAME=$2
SSH_PORT=$3
CERTBOT_EMAIL=$4

PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 63)

CWD=$(pwd)

apt-get update && apt-get -y upgrade
apt-get install -y unattended-upgrades build-essential git gnupg autossh

# Initiate firewall with UFW.
# Each module is in charge of their network access. Rules are
# enabled at the end of the script.
yes | ufw reset

# Do hosts things
. hosts

# Do users stuff
. users

# Lock SSH access down
. ssh

read -p "Web?" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  . nginx 
#  . php
fi

#read -p "MySQL? " -n 1 -r
#echo    # (optional) move to a new line
#if [[ $REPLY =~ ^[Yy]$ ]]
#then
#  . mysql
#fi

#read -p "Python? " -n 1 -r
#echo    # (optional) move to a new line
#if [[ $REPLY =~ ^[Yy]$ ]]
#then
#  . python
#fi

echo "Activating firewall"
yes | ufw enable
