#!/usr/bin/env bash
HISTSIZE=0
set +o history

apt update && apt install -y nginx certbot python3-certbot-nginx

# back up files before fsking them
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.before.bjorg
mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.before.bjorg

# spew the template files in to place
cat "$CWD"/templates/index.html > /var/www/html/index.html
cat "$CWD"/templates/nginx.conf > /etc/nginx/nginx.conf
cat "$CWD"/templates/default > /etc/nginx/sites-available/default
# update FQDN
sed -i 's/server_name _.*/server_name '"$FQDN"';/' /etc/nginx/sites-available/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# update firewall rules to allow connection
ufw allow 80/tcp
ufw allow 443/tcp

service nginx stop
service nginx start

# Request SSL
echo "Setting up SSL ..."
certbot -n --agree-tos --email "$CERTBOT_EMAIL" --authenticator webroot -w /var/www/html/ --installer nginx --redirect --hsts --uir --domain "$FQDN"