#!/usr/bin/env bash
HISTSIZE=0
set +o history

# assumes access only via ipv4 because that is the only one i care about right now
# (todo v6)

file=/etc/ssh/sshd_config

# back up config first
cp $file /etc/ssh/ssh_config.before.bjorg

# do not allow root to log in
sed -i 's/PermitRootLogin .*/PermitRootLogin no/' $file

# do not allow password authentication
sed -i 's/#PasswordAuthentication .*/PasswordAuthentication no/' $file

# resist default port
sed -i 's/#Port .*/Port '"$SSH_PORT"'/' $file

# explicitly set access interface
sed -i 's/#AddressFamily .*/#AddressFamily inet/' $file

# update firewall rules to allow connection
ufw allow $SSH_PORT/tcp
